fixtures:
  repositories:
    apt: 'git://github.com/puppetlabs/puppetlabs-apt'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat'
    epel: 'https://github.com/stahnma/puppet-module-epel'
